#!/bin/bash

# ============================================================================
# NOTIFICATION SYSTEM DEBUGGING SCRIPT
# ============================================================================
# 
# This script helps diagnose why notifications aren't working
# Run this on your device while testing notifications
#

set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  NOTIFICATION DEBUGGING CHECKLIST                             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}\n"

echo -e "${YELLOW}STEP 1: CHECK SERVICE WORKER INSTALLATION${NC}"
echo "In browser DevTools:"
echo "  1. Press F12 (or Cmd+Option+I on Mac)"
echo "  2. Go to: Application → Service Workers"
echo "  3. Should see: service-worker.js with status 'activated and running'"
echo "  4. If red/inactive:"
echo "     - Click 'Unregister'"
echo "     - Hard refresh (Ctrl+Shift+R)"
echo "     - Reload page"
echo ""

echo -e "${YELLOW}STEP 2: CHECK NOTIFICATION PERMISSION${NC}"
echo "In browser DevTools:"
echo "  1. Go to: Application → Manifest"
echo "  2. Look for: 'permissions' section"
echo "  3. Or go to: Settings → Notifications → Find your app"
echo "  4. Ensure 'Allowed' is selected"
echo ""
echo "If permission is 'Blocked':"
echo "  - Click the 🔒 icon in address bar"
echo "  - Find 'Notifications' → Change to 'Allow'"
echo "  - Refresh page"
echo "  - Try again"
echo ""

echo -e "${YELLOW}STEP 3: CHECK PUSH SUBSCRIPTION${NC}"
echo "In browser DevTools:"
echo "  1. Go to: Console"
echo "  2. Look for messages:"
echo "     '[PushService] Subscription saved to backend'"
echo "     '[ServiceWorker] Installing...'"
echo "     '[ServiceWorker] Activating...'"
echo ""
echo "If NOT seeing these messages:"
echo "  - Check browser console for errors"
echo "  - Try enabling notifications (bell icon) again"
echo "  - Look for any RED error messages"
echo ""

echo -e "${YELLOW}STEP 4: CHECK DATABASE SUBSCRIPTION${NC}"
echo "Go to: Supabase Dashboard"
echo "  1. Navigate to: Database → Tables → push_subscriptions"
echo "  2. Should see rows with:"
echo "     - endpoint (URL)"
echo "     - p256dh (encryption key)"
echo "     - auth (auth token)"
echo "     - salon_id (should match your salon)"
echo "     - platform (ios/android/desktop)"
echo ""
echo "If table is EMPTY:"
echo "  - Subscription wasn't saved"
echo "  - Check console logs in step 3"
echo ""

echo -e "${YELLOW}STEP 5: TEST BOOKING CREATION${NC}"
echo "Now test by creating a booking:"
echo "  1. On ANOTHER device/browser go to: /book page"
echo "  2. Fill in booking details"
echo "  3. Tap 'CONFIRM BOOKING'"
echo "  4. Watch your first device for notification"
echo ""

echo -e "${YELLOW}STEP 6: CHECK EDGE FUNCTION LOGS${NC}"
echo "If booking was created but no notification:"
echo "  1. Open terminal"
echo "  2. Run:"
echo "     supabase functions logs send-push-notification --project-ref czvsgtvienmchudyzqpk"
echo "  3. Look for errors about:"
echo "     - VAPID signing"
echo "     - AES-GCM encryption"
echo "     - HTTP POST to endpoints"
echo "     - 'No subscriptions found'"
echo ""

echo -e "${YELLOW}STEP 7: BROWSER CONSOLE DURING BOOKING${NC}"
echo "Keep DevTools Console open while creating booking:"
echo "  1. Watch for messages starting with:"
echo "     [ServiceWorker] 🔔 Push received"
echo "     [ServiceWorker] ✅ Notification shown"
echo "     [App] 🔊 Playing notification sound"
echo ""
echo "If seeing errors:"
echo "  - Copy the error message"
echo "  - Search the error in our code"
echo "  - Could indicate permission or sound issue"
echo ""

echo -e "${YELLOW}STEP 8: COMMON ISSUES & SOLUTIONS${NC}\n"

echo -e "${RED}Issue: Notification permission is 'Blocked'${NC}"
echo "  Solution:"
echo "    • Click lock icon in address bar"
echo "    • Change notifications to 'Allow'"
echo "    • Refresh page"
echo "    • Try again"
echo ""

echo -e "${RED}Issue: Service Worker shows red/inactive${NC}"
echo "  Solution:"
echo "    • Click 'Unregister'"
echo "    • Hard refresh: Ctrl+Shift+R (Windows) or Cmd+Shift+R (Mac)"
echo "    • Wait 5 seconds"
echo "    • Reload"
echo ""

echo -e "${RED}Issue: 'No subscriptions found' in edge function logs${NC}"
echo "  Solution:"
echo "    • Subscription wasn't saved to database"
echo "    • Check push_subscriptions table (empty?)"
echo "    • Try enabling notifications again"
echo "    • Check console for 'Subscription saved' message"
echo ""

echo -e "${RED}Issue: No sound plays${NC}"
echo "  Solution:"
echo "    • Check device volume (not silent mode)"
echo "    • Check browser settings haven't muted audio"
echo "    • Check notification.mp3 file exists in build"
echo "    • Try on different browser"
echo ""

echo -e "${RED}Issue: Device doesn't have app installed as PWA${NC}"
echo "  Solution:"
echo "    • Background push only works when PWA is installed"
echo "    • Install PWA: Open in browser → Menu → 'Install app'"
echo "    • Or: iOS → Safari → Share → Add to Home Screen"
echo ""

echo -e "${RED}Issue: iOS notifications not working${NC}"
echo "  Solution:"
echo "    • Need iOS 16.4+ (Web Push support)"
echo "    • Use Safari (not Chrome)"
echo "    • Install as PWA via Add to Home Screen"
echo "    • Check Settings → Notifications → Safari"
echo ""

echo -e "${YELLOW}STEP 9: QUICK TEST CHECKLIST${NC}\n"

echo "Before testing, verify:"
echo "  ✓ [ ] PWA is installed on device (not just browser tab)"
echo "  ✓ [ ] Notifications permission is 'Allow'"
echo "  ✓ [ ] Service Worker is 'activated and running'"
echo "  ✓ [ ] Bell icon is visible in navbar"
echo "  ✓ [ ] Bell icon is GREEN (notifications enabled)"
echo "  ✓ [ ] Console shows 'Subscription saved'"
echo "  ✓ [ ] Supabase push_subscriptions table has entry for your user"
echo "  ✓ [ ] Device volume is ON (not silent mode)"
echo ""

echo -e "${YELLOW}STEP 10: IF STILL NOT WORKING${NC}"
echo ""
echo "Run edge function logs and share output:"
echo "  supabase functions logs send-push-notification --project-ref czvsgtvienmchudyzqpk"
echo ""
echo "Share browser console errors (F12 → Console):"
echo "  Look for: [ServiceWorker] ❌ or [PushService] errors"
echo ""
echo "Check if subscription exists:"
echo "  Supabase → Database → push_subscriptions table"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Debugging guide complete. Follow steps above to diagnose issue.${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
