#!/bin/bash

# Runway Deployment Quick Reference
# ===================================

echo "=== RUNWAY DEPLOYMENT CHECKLIST ==="
echo ""

echo "1. MONGODB ATLAS SETUP"
echo "   [ ] Visit: https://www.mongodb.com/cloud/atlas"
echo "   [ ] Create free cluster (M0 tier)"
echo "   [ ] Get connection string with credentials"
echo "   [ ] Whitelist IP: 0.0.0.0/0"
echo "   [ ] Save connection string for later"
echo ""

echo "2. BACKEND PREPARATION"
echo "   [ ] Verify Dockerfile is multi-stage"
echo "   [ ] Verify .env.example has all variables"
echo "   [ ] Commit changes: git add . && git commit -m 'Deploy: Runway setup'"
echo "   [ ] Push to main: git push origin main"
echo ""

echo "3. GENERATE SECURE JWT SECRET"
echo "   Run this command and copy the output:"
echo "   node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""

echo "4. RUNWAY DEPLOYMENT"
echo "   [ ] Visit: https://runway.dev"
echo "   [ ] Sign up and connect GitHub"
echo "   [ ] Create new project from montaassarr/barber"
echo "   [ ] Set service directory: barber-backend-node"
echo "   [ ] Build command: npm run build"
echo "   [ ] Start command: node dist/server.js"
echo ""

echo "5. SET RUNWAY ENVIRONMENT VARIABLES"
echo "   Add these in Runway Dashboard:"
echo ""
echo "   NODE_ENV                      = production"
echo "   PORT                          = 4000"
echo "   MONGODB_URI                   = <from MongoDB Atlas>"
echo "   JWT_SECRET                    = <generated above>"
echo "   JWT_EXPIRES_IN                = 7d"
echo "   CORS_ORIGIN                   = https://<your-vercel-url>.vercel.app"
echo "   SEED_ADMIN_EMAIL              = owner@barbershop.com"
echo "   SEED_ADMIN_PASSWORD           = <secure password>"
echo "   SEED_SALON_NAME               = Demo Salon"
echo "   SEED_SALON_SLUG               = demo-salon"
echo "   SEED_SUPER_ADMIN_EMAIL        = superadmin@barbershop.com"
echo "   SEED_SUPER_ADMIN_PASSWORD     = <secure password>"
echo ""

echo "6. DEPLOY TO RUNWAY"
echo "   [ ] Click 'Deploy' in Runway dashboard"
echo "   [ ] Wait for build and deployment (~2-3 min)"
echo "   [ ] Get your API URL (e.g., https://your-id.runway.app)"
echo ""

echo "7. UPDATE VERCEL FRONTEND"
echo "   [ ] Go to Vercel project settings"
echo "   [ ] Add environment variable:"
echo "       VITE_API_BASE_URL = <your Runway API URL>"
echo "   [ ] Redeploy: git push origin main"
echo ""

echo "8. VERIFICATION"
echo "   [ ] Test health endpoint:"
echo "       curl https://<runway-url>/health"
echo "   [ ] Open frontend in browser"
echo "   [ ] Try logging in"
echo "   [ ] Check browser console for errors"
echo ""

echo "9. ONGOING"
echo "   [ ] Monitor Runway logs for errors"
echo "   [ ] Check MongoDB Atlas metrics"
echo "   [ ] Set up backup strategy"
echo ""

echo "=== HELPFUL LINKS ==="
echo "MongoDB Atlas:     https://www.mongodb.com/cloud/atlas"
echo "Runway Docs:       https://docs.runway.dev"
echo "Vercel Docs:       https://vercel.com/docs"
echo ""
