
create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    endpoint text not null unique,
    p256dh text not null,
    auth text not null,
    user_agent text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    last_used_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.push_subscriptions enable row level security;

create policy "Users can insert their own subscriptions"
on public.push_subscriptions for insert
with check (auth.uid() = user_id);

create policy "Users can view their own subscriptions"
on public.push_subscriptions for select
using (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
on public.push_subscriptions for delete
using (auth.uid() = user_id);

-- Create index for faster lookup by user_id
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
