-- Add is_super_admin column to staff table
ALTER TABLE public.staff 
ADD COLUMN IF NOT EXISTS is_super_admin boolean DEFAULT false;

-- Add role column if it doesn't exist (just in case)
ALTER TABLE public.staff 
ADD COLUMN IF NOT EXISTS role text DEFAULT 'staff';

-- Ensure the Super Admin user exists (Idempotent)
-- We use a DO block to handle the insertion conditionally or via ON CONFLICT if the ID is known
-- Since IDs are UUIDs generated by Auth, we strictly can't insert into auth.users here safely in a migration
-- But we can update the public.staff table if we assume the user exists in Auth.

-- Create policies for Super Admin if not exist
-- (Simple permissive policy for now to ensure access)
DROP POLICY IF EXISTS "Super admins can do everything" ON public.staff;
CREATE POLICY "Super admins can do everything" 
ON public.staff 
FOR ALL 
USING (is_super_admin = true);

DROP POLICY IF EXISTS "Super admins can view all salons" ON public.salons;
CREATE POLICY "Super admins can view all salons" 
ON public.salons 
FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.staff 
    WHERE id = auth.uid() AND is_super_admin = true
  )
);
